"""add_correos_propios_table

Revision ID: 1a7e05600495
Revises: e224d5c09bc6
Create Date: 2026-07-13 17:59:38.812478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add_correos_propios_table

Revision ID: 1a7e05600495
Revises: e224d5c09bc6
Create Date: 2026-07-13 17:59:38.812478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a7e05600495'
down_revision: Union[str, Sequence[str], None] = 'e224d5c09bc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correos_propios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correo_gmail', sa.String(length=150), nullable=False),
    sa.Column('password_gmail', sa.String(length=255), nullable=False),
    sa.Column('correo_verificacion', sa.String(length=150), nullable=True),
    sa.Column('numero_asociado', sa.String(length=50), nullable=True),
    sa.Column('ultimo_ingreso', sa.Date(), nullable=True),
    sa.Column('pide_validacion', sa.Boolean(), nullable=False),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('notas_pago_netflix', sa.Text(), nullable=True),
    sa.Column('nombre_correo', sa.String(length=150), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('sexo', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_correos_propios')),
    sa.UniqueConstraint('correo_gmail', name=op.f('uq_correos_propios_correo_gmail'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('correos_propios')
    # ### end Alembic commands ###
