"""add_garantia_proveedor_table

Revision ID: 254610c8ed15
Revises: 6f7a47527cdc
Create Date: 2026-07-02 22:29:23.709918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '254610c8ed15'
down_revision: Union[str, Sequence[str], None] = '6f7a47527cdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('garantias_proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_madre_id', sa.Integer(), nullable=False),
    sa.Column('tipo_garantia', sa.String(length=50), nullable=False),
    sa.Column('monto_saldo_a_favor', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('resuelto', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cuenta_madre_id'], ['cuentas_madre.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('garantias_proveedores')
    # ### end Alembic commands ###
