"""add_reportado_to_perfil

Revision ID: 6f7a47527cdc
Revises: c796622e8114
Create Date: 2026-07-02 22:15:57.010733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f7a47527cdc'
down_revision: Union[str, Sequence[str], None] = 'c796622e8114'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perfiles', sa.Column('reportado', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('perfiles', 'reportado')
    # ### end Alembic commands ###
