"""add_cuentas_madres_canceladas

Revision ID: 99e8ff098b49
Revises: a0d67a960d1d
Create Date: 2026-07-15 22:44:04.903662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add_cuentas_madres_canceladas

Revision ID: 99e8ff098b49
Revises: a0d67a960d1d
Create Date: 2026-07-15 22:44:04.903662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99e8ff098b49'
down_revision: Union[str, Sequence[str], None] = 'a0d67a960d1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuentas_madres_canceladas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_madre_id', sa.Integer(), nullable=False),
    sa.Column('plataforma_nombre', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('clave', sa.String(length=150), nullable=False),
    sa.Column('max_perfiles', sa.Integer(), nullable=False),
    sa.Column('proveedor_nombre', sa.String(length=100), nullable=False),
    sa.Column('precio_compra', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha_compra', sa.Date(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('fecha_cancelacion', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('motivo_cancelacion', sa.Text(), nullable=True),
    sa.Column('devolucion_caja', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('devolucion_proveedor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cuentas_madres_canceladas'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cuentas_madres_canceladas')
    # ### end Alembic commands ###
