"""add_clave_plataforma_correos_propios_table

Revision ID: a0d67a960d1d
Revises: e452110d1511
Create Date: 2026-07-14 19:45:00.919789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add_clave_plataforma_correos_propios_table

Revision ID: a0d67a960d1d
Revises: e452110d1511
Create Date: 2026-07-14 19:45:00.919789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0d67a960d1d'
down_revision: Union[str, Sequence[str], None] = 'e452110d1511'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clave_plataforma_correos_propios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correo_propio_id', sa.Integer(), nullable=False),
    sa.Column('plataforma_id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['correo_propio_id'], ['correos_propios.id'], name=op.f('fk_clave_plataforma_correos_propios_correo_propio_id_correos_propios'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plataforma_id'], ['plataformas.id'], name=op.f('fk_clave_plataforma_correos_propios_plataforma_id_plataformas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clave_plataforma_correos_propios')),
    sa.UniqueConstraint('correo_propio_id', 'plataforma_id', name='uq_correo_plataforma')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clave_plataforma_correos_propios')
    # ### end Alembic commands ###
