"""add_nullable_tipo_venta_to_venta

Revision ID: bba7b8ca9217
Revises: 9a9c6a74ed4f
Create Date: 2026-07-08 19:59:28.372971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bba7b8ca9217'
down_revision: Union[str, Sequence[str], None] = '9a9c6a74ed4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ventas', sa.Column('tipo_venta', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ventas', 'tipo_venta')
    # ### end Alembic commands ###
