"""initial

Revision ID: c796622e8114
Revises: 
Create Date: 2026-07-02 16:11:58.286728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c796622e8114'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.Enum('FINAL', 'REVENDEDOR', name='tipo_cliente'), nullable=False),
    sa.Column('estado', sa.Enum('ACTIVO', 'BANEADO', name='estado_cliente'), nullable=False),
    sa.Column('dias_gracia_max', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telefono')
    )
    op.create_table('combos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('precio_combo', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credenciales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('plantillas_mensajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('plataformas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('saldo_a_favor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint('saldo_a_favor >= 0', name='check_saldo_positivo'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telefono')
    )
    op.create_table('transacciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('entidad', sa.Enum('NEQUI', 'BANCOLOMBIA', 'DAVIPLATA', 'NU_BANK', 'EFECTIVO', name='entidad_financiera'), nullable=False),
    sa.Column('referencia_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.CheckConstraint("tipo IN ('INGRESO', 'EGRESO')", name='check_tipo_transaccion'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cuentas_madre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('credencial_id', sa.Integer(), nullable=False),
    sa.Column('plataforma_id', sa.Integer(), nullable=False),
    sa.Column('max_perfiles', sa.Integer(), nullable=False),
    sa.Column('precio_compra', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha_compra', sa.Date(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('ACTIVA', 'CAIDA', 'VENCIDA', 'RENOVADA', name='estado_cuenta'), nullable=False),
    sa.ForeignKeyConstraint(['credencial_id'], ['credenciales.id'], ),
    sa.ForeignKeyConstraint(['plataforma_id'], ['plataformas.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('fecha_corte', sa.Date(), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado_pago', sa.Enum('PAGADO', 'PENDIENTE', 'DIAS_ESPERA', 'PAGO_PARCIAL', name='estado_pago'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagos_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('entidad', sa.Enum('NEQUI', 'BANCOLOMBIA', 'DAVIPLATA', 'NU_BANK', 'EFECTIVO', name='entidad_financiera'), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perfiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cuenta_madre_id', sa.Integer(), nullable=False),
    sa.Column('nombre_perfil', sa.String(length=50), nullable=False),
    sa.Column('pin', sa.String(length=10), nullable=True),
    sa.Column('asignado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cuenta_madre_id'], ['cuentas_madre.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cuenta_madre_id', 'nombre_perfil', name='uq_cuenta_madre_perfil')
    )
    op.create_table('detalles_venta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('combo_id', sa.Integer(), nullable=True),
    sa.Column('cuenta_madre_id', sa.Integer(), nullable=True),
    sa.Column('perfil_id', sa.Integer(), nullable=True),
    sa.Column('precio_aplicado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['combo_id'], ['combos.id'], ),
    sa.ForeignKeyConstraint(['cuenta_madre_id'], ['cuentas_madre.id'], ),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfiles.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('garantias_clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detalle_venta_id', sa.Integer(), nullable=False),
    sa.Column('perfil_anterior_id', sa.Integer(), nullable=False),
    sa.Column('perfil_nuevo_id', sa.Integer(), nullable=True),
    sa.Column('dias_extendidos', sa.Integer(), nullable=False),
    sa.Column('resuelto', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['detalle_venta_id'], ['detalles_venta.id'], ),
    sa.ForeignKeyConstraint(['perfil_anterior_id'], ['perfiles.id'], ),
    sa.ForeignKeyConstraint(['perfil_nuevo_id'], ['perfiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('garantias_clientes')
    op.drop_table('detalles_venta')
    op.drop_table('perfiles')
    op.drop_table('pagos_venta')
    op.drop_table('ventas')
    op.drop_table('cuentas_madre')
    op.drop_table('transacciones')
    op.drop_table('proveedores')
    op.drop_table('plataformas')
    op.drop_table('plantillas_mensajes')
    op.drop_table('credenciales')
    op.drop_table('combos')
    op.drop_table('clientes')
    # ### end Alembic commands ###
