"""add_ventas_vencidas_table

Revision ID: e224d5c09bc6
Revises: f09477e9511b
Create Date: 2026-07-13 17:37:00.710281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add_ventas_vencidas_table

Revision ID: e224d5c09bc6
Revises: f09477e9511b
Create Date: 2026-07-13 17:37:00.710281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e224d5c09bc6'
down_revision: Union[str, Sequence[str], None] = 'f09477e9511b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ventas_vencidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente', sa.String(length=150), nullable=False),
    sa.Column('monto_pagado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('plataforma', sa.String(length=100), nullable=False),
    sa.Column('cuenta_madre', sa.String(length=150), nullable=False),
    sa.Column('fecha_corte_registro', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ventas_vencidas'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ventas_vencidas')
    # ### end Alembic commands ###
