"""add_nota_column_to_ventas

Revision ID: e452110d1511
Revises: e9546c129edf
Create Date: 2026-07-13 18:27:44.500574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add_nota_column_to_ventas

Revision ID: e452110d1511
Revises: e9546c129edf
Create Date: 2026-07-13 18:27:44.500574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e452110d1511'
down_revision: Union[str, Sequence[str], None] = 'e9546c129edf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ventas', sa.Column('nota', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ventas', 'nota')
    # ### end Alembic commands ###
