"""add_notas_and_proveedores_links

Revision ID: e9546c129edf
Revises: 1a7e05600495
Create Date: 2026-07-13 18:21:57.060597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add_notas_and_proveedores_links

Revision ID: e9546c129edf
Revises: 1a7e05600495
Create Date: 2026-07-13 18:21:57.060597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9546c129edf'
down_revision: Union[str, Sequence[str], None] = '1a7e05600495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notas_ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notas_ventas'))
    )
    op.create_table('enlaces_proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], name=op.f('fk_enlaces_proveedores_proveedor_id_proveedores'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enlaces_proveedores'))
    )
    op.add_column('proveedores', sa.Column('observaciones', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proveedores', 'observaciones')
    op.drop_table('enlaces_proveedores')
    op.drop_table('notas_ventas')
    # ### end Alembic commands ###
